---

- name: update the system and install docker
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
  
    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
  
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true


    - name: Install the Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose
        executable: pip3 

    - name: add the machine user to docker group
      user: 
        name: vagrant
        group: docker

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'


    - name: Copy inception project
      copy:
        src: ../inception_project
        dest: /home/cloud/

    - name: Run docker-compose up
      environment:
        ip: "{{ inventory_hostname }}"
      community.docker.docker_compose_v2:
        project_src: /home/cloud/inception/srcs
        build: always

