---

- name: update the system and install docker
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: update system and install docker 
      package:
        name:
          - docker.io
          - python3-pip
        update_cache: true


    - name: Install the Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose
        executable: pip3 

    - name: add the machine user to docker group
      user: 
        name: vagrant
        group: docker

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'


    - name: Copy inception project
      copy:
        src: ../inception
        dest: /home/cloud/

    - name: Run docker-compose up
      environment:
        ip: "{{ inventory_hostname }}"
      docker_compose:
        project_src: /home/vagrant/inception/srcs

